name: wtnews
description: War Thunder News application

publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  window_manager: ^0.3.1
  shared_preferences: ^2.0.13
  local_notifier:
    path: ../local_notifier
  tray_manager: ^0.2.0
  archive: ^3.3.0
  url_launcher: ^6.1.0
  flutter_riverpod: ^2.1.3
  win32: ^4.1.1
  file_picker: ^5.2.5
  firebase_dart: ^1.0.9
  firebase_dart_flutter:
  firebase_core: ^2.7.0
  device_info_plus: ^8.1.0
  sentry_flutter: ^6.9.1
  flutter_acrylic: ^1.1.0+1
  path: ^1.8.1
  ffi: ^2.0.1
  path_provider: ^2.0.13
  blinking_text: ^1.0.2
  intl: ^0.17.0
  fluent_ui: ^4.4.0
  system_theme: ^2.1.0
  dynamic_color: ^1.6.2
  system_info2: ^3.0.1
  cached_network_image: ^3.2.1
  contextmenu: ^3.0.0
  web_socket_channel: ^2.3.0
  equatable: ^2.0.5
  flutter_tts: ^3.6.3
  webview_windows: ^0.2.2
  hotkey_manager: ^0.1.7

dependency_overrides:
  win32: 4.1.1

dev_dependencies:

  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/install/
    - assets/sound/
